# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/banque_sang
spring.datasource.username=postgres
spring.datasource.password=farah
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# DEBUG SQL (optionnel)
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
